name: Lite Check
on:
  workflow_dispatch:
jobs:
  build:
    name: Run Auto Test
    runs-on: windows-latest
    outputs:
      result: ${{ steps.sum.outputs.foshia }}
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Simple job summary
      run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
    - uses: actions/checkout@v2
    - name: Build Auto Test
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install NPM
      run: npm ci
    - name: Run Test
      id: run_md_lint
      run: |
          echo "::set-output name=TAG_NAME::$(npm test)"
    - name: SUM Test
      uses: actions/github-script@v5
      id: sum
      with:
          script: |
            core.setOutput("foshia", `${{ steps.run_md_lint.outputs.TAG_NAME }}`);

  summary:
    name: Summary
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Simple job summary
      run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
    - name: Run a one-line script
      run: echo "Resultes ${{needs.build.outputs.result}}" >> $GITHUB_STEP_SUMMARY
